### ISSUE TITLE
How do I run the C++ demos on OSX?

### ISSUE THREAD

**Issue by danielytics** [GodotNativeTools/GDNative-demos#20]
I compiled the cpp/SimpleDemo code using `scons platform=osx` and I edited the `.gdnlib` file from the Godot editor to add the `.dylib` file, but when I then try to run the demo, I get the error `does not have a library for the current platform`. Am I missing something?

**Comment by karroffel** [comment]
Did you save the gdnlib file properly?

**Comment by danielytics** [comment]
Ahhhh... I thought I had, but when I double checked by opening the file outside of Godot, I saw it wasn't saved. Now it works! Godot editor could definitely do with a UX improvement here. Thanks for pointing me in the right direction. Now to see why my own test project didn't work, I assume its a similar issue since I was getting the same error, but now that I have a working demo, I should be able to figure it out 👍
